### ISSUE TITLE
Error on Install private SSH Keys

### ISSUE THREAD

**Issue by NathanOrme** [mpereira/macbook-playbook#1]
Get the following error output from ansible task:
TASK [ssh-keys : Install private SSH keys] ******************************************************************************************************************************************
fatal: [localhost]: FAILED! => 
  msg: Decryption failed (no vault secrets were found that could decrypt) on /Users/nathanorme/Documents/macbook-playbook/roles/ssh-keys/files/id_rsa

**Comment by RGBNathan** [comment]
<img width="1280" alt="Screenshot 2019-06-15 at 11 53 37" src="https://user-images.githubusercontent.com/18661760/59550619-94f38680-8f64-11e9-8614-a3f6786328b7.png">

**Comment by RGBNathan** [comment]
Am I missing something on the setup?

**Comment by mpereira** [comment]
Hey @NathanOrme,

Thanks for trying out macbook-playbook! The existing encrypted files in this project are encrypted with my credentials, so unless you have them they won't be able to be unencrypted. One thing you can try is to remove them (`roles/ssh-keys/files/id_rsa` for example), create your own, and then run `make encrypt`, which will encrypt them based on your `.ansible_vault_password`.

I plan on making this more accessible for people other than me soon. Also, please check out the latest changes that I pushed. It is now possible to install things based on tags. For example, `make converge ARGS='--tags git'` will only converge the `git` role. Check out the [main.yml](https://github.com/mpereira/macbook-playbook/blob/master/main.yml) file for more details.

**Comment by mpereira** [comment]
I added some instructions re: encrypted files [in the README](https://github.com/mpereira/macbook-playbook#encrypted-files-using-ansible-vault).
